// <auto-generated />
using System;
using DMO.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DMO.Infrastructure.Migrations
{
    [DbContext(typeof(DmoDbContext))]
    [Migration("20260925071139_ControloComparacaoDomain")]
    partial class ControloComparacaoDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.AdminAccountEntity", b =>
                {
                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("AuthIdentityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_identity_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("AdminId");

                    b.HasIndex("Active")
                        .HasDatabaseName("admin_accounts_active_idx")
                        .HasFilter("\"active\"");

                    b.HasIndex("AuthIdentityId")
                        .IsUnique()
                        .HasDatabaseName("admin_accounts_auth_identity_id_key");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("admin_accounts_email_key");

                    b.ToTable("admin_accounts", null, t =>
                        {
                            t.HasCheckConstraint("admin_accounts_auth_identity_id_required_check", "btrim(auth_identity_id) <> ''");

                            t.HasCheckConstraint("admin_accounts_email_required_check", "btrim(email) <> ''");

                            t.HasCheckConstraint("admin_accounts_singleton_id_check", "admin_id = '00000000-0000-4000-8000-0000000000ad'::uuid");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.BoquilhaEntity", b =>
                {
                    b.Property<Guid>("BoquilhasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("boquilhas_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BqId")
                        .HasColumnType("uuid")
                        .HasColumnName("bq_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("ToolId")
                        .HasColumnType("uuid")
                        .HasColumnName("tool_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("BoquilhasId");

                    b.HasIndex("BqId")
                        .IsUnique()
                        .HasDatabaseName("boquilhas_bq_id_key");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_boquilhas_created_at");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ToolId")
                        .HasDatabaseName("IX_boquilhas_tool_id");

                    b.ToTable("boquilhas", null, t =>
                        {
                            t.HasCheckConstraint("boquilhas_anchor_check", "(bq_id IS NULL) <> (tool_id IS NULL)");

                            t.HasCheckConstraint("boquilhas_version_check", "version >= 1");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.BoquilhaMovementAuditEntity", b =>
                {
                    b.Property<Guid>("MovementAuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("movement_audit_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly>("AfterBusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("after_business_date");

                    b.Property<string>("AfterMachine")
                        .HasColumnType("text")
                        .HasColumnName("after_machine");

                    b.Property<string>("AfterObservations")
                        .HasColumnType("text")
                        .HasColumnName("after_observations");

                    b.Property<int>("AfterQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("after_quantity");

                    b.Property<Guid?>("AfterRepairerId")
                        .HasColumnType("uuid")
                        .HasColumnName("after_repairer_id");

                    b.Property<DateOnly>("BeforeBusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("before_business_date");

                    b.Property<string>("BeforeMachine")
                        .HasColumnType("text")
                        .HasColumnName("before_machine");

                    b.Property<string>("BeforeObservations")
                        .HasColumnType("text")
                        .HasColumnName("before_observations");

                    b.Property<int>("BeforeQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("before_quantity");

                    b.Property<Guid?>("BeforeRepairerId")
                        .HasColumnType("uuid")
                        .HasColumnName("before_repairer_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<Guid>("EditedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("edited_by_user_id");

                    b.Property<Guid>("MovementId")
                        .HasColumnType("uuid")
                        .HasColumnName("movement_id");

                    b.HasKey("MovementAuditId");

                    b.HasIndex("EditedByUserId");

                    b.HasIndex("MovementId", "EditedAt")
                        .HasDatabaseName("IX_boquilha_movement_audit_movement_id");

                    b.ToTable("boquilha_movement_audit", null, t =>
                        {
                            t.HasCheckConstraint("boquilha_movement_audit_quantities_check", "before_quantity > 0 AND after_quantity > 0");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.BoquilhaMovementEntity", b =>
                {
                    b.Property<Guid>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("movement_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BoquilhasId")
                        .HasColumnType("uuid")
                        .HasColumnName("boquilhas_id");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("business_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Machine")
                        .HasColumnType("text")
                        .HasColumnName("machine");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("movement_type");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<Guid?>("RepairerId")
                        .HasColumnType("uuid")
                        .HasColumnName("repairer_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("MovementId");

                    b.HasIndex("RecordedByUserId");

                    b.HasIndex("RepairerId");

                    b.HasIndex("BoquilhasId", "RecordedAt", "MovementId")
                        .HasDatabaseName("IX_boquilha_movements_boquilhas_id");

                    b.ToTable("boquilha_movements", null, t =>
                        {
                            t.HasCheckConstraint("boquilha_movements_machine_check", "machine IS NULL OR machine IN ('B1','B2','B3','C1','C2','C3')");

                            t.HasCheckConstraint("boquilha_movements_observations_check", "observations IS NULL OR btrim(observations) <> ''");

                            t.HasCheckConstraint("boquilha_movements_quantity_check", "quantity > 0");

                            t.HasCheckConstraint("boquilha_movements_saida_required_check", "NOT (movement_type = 'saida' AND (machine IS NULL OR repairer_id IS NULL))");

                            t.HasCheckConstraint("boquilha_movements_type_check", "movement_type IN ('saida','entrada','entrada_sem_reparacao')");

                            t.HasCheckConstraint("boquilha_movements_version_check", "version >= 1");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.BqContextEntity", b =>
                {
                    b.Property<Guid>("BqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("bq_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("JobOnId")
                        .HasColumnType("uuid")
                        .HasColumnName("jobon_id");

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uuid")
                        .HasColumnName("tool_id");

                    b.Property<string>("ToolLot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_lot");

                    b.Property<string>("ToolReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_reference");

                    b.Property<string>("ToolType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("BqId");

                    b.HasIndex("JobOnId")
                        .IsUnique()
                        .HasDatabaseName("bq_contexts_jobon_key");

                    b.HasIndex("ToolId")
                        .HasDatabaseName("IX_bq_contexts_tool_id");

                    b.ToTable("bq_contexts", null, t =>
                        {
                            t.HasCheckConstraint("bq_contexts_tool_lot_required_check", "btrim(tool_lot) <> ''");

                            t.HasCheckConstraint("bq_contexts_tool_reference_required_check", "btrim(tool_reference) <> ''");

                            t.HasCheckConstraint("bq_contexts_tool_type_check", "tool_type = 'BQ'");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.CmContextEntity", b =>
                {
                    b.Property<Guid>("CmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cm_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("JobOnId")
                        .HasColumnType("uuid")
                        .HasColumnName("jobon_id");

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uuid")
                        .HasColumnName("tool_id");

                    b.Property<string>("ToolLot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_lot");

                    b.Property<string>("ToolReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_reference");

                    b.Property<string>("ToolType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CmId");

                    b.HasIndex("JobOnId")
                        .IsUnique()
                        .HasDatabaseName("cm_contexts_jobon_key");

                    b.HasIndex("ToolId")
                        .HasDatabaseName("IX_cm_contexts_tool_id");

                    b.ToTable("cm_contexts", null, t =>
                        {
                            t.HasCheckConstraint("cm_contexts_tool_lot_required_check", "btrim(tool_lot) <> ''");

                            t.HasCheckConstraint("cm_contexts_tool_reference_required_check", "btrim(tool_reference) <> ''");

                            t.HasCheckConstraint("cm_contexts_tool_type_check", "tool_type = 'CM'");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.ComparacaoCmSubjectEntity", b =>
                {
                    b.Property<Guid>("ComparacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparacao_id");

                    b.Property<Guid>("CmId")
                        .HasColumnType("uuid")
                        .HasColumnName("cm_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<string>("Decision")
                        .HasColumnType("text")
                        .HasColumnName("decision");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("ComparacaoId", "CmId");

                    b.HasIndex("CmId")
                        .HasDatabaseName("IX_comparacao_cm_subjects_cm_id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DecidedByUserId");

                    b.ToTable("comparacao_cm_subjects", null, t =>
                        {
                            t.HasCheckConstraint("comparacao_cm_subjects_decision_check", "decision IS NULL OR decision IN ('manter','colocar_de_parte')");

                            t.HasCheckConstraint("comparacao_cm_subjects_decision_state_check", "(decision IS NULL AND decided_by_user_id IS NULL AND decided_at IS NULL) OR (decision IS NOT NULL AND decided_by_user_id IS NOT NULL AND decided_at IS NOT NULL)");

                            t.HasCheckConstraint("comparacao_cm_subjects_reason_check", "decision IS NULL OR decision <> 'colocar_de_parte' OR (reason IS NOT NULL AND btrim(reason) <> '')");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.ComparacaoEntity", b =>
                {
                    b.Property<Guid>("ComparacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("comparacao_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("PesoId")
                        .HasColumnType("uuid")
                        .HasColumnName("peso_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("ComparacaoId");

                    b.HasIndex("ConfirmedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PesoId")
                        .HasDatabaseName("IX_comparacoes_peso_id");

                    b.ToTable("comparacoes", null, t =>
                        {
                            t.HasCheckConstraint("comparacoes_confirmed_check", "(confirmed_at IS NULL AND confirmed_by_user_id IS NULL) OR (confirmed_at IS NOT NULL AND confirmed_by_user_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.ComparacaoMeasurementRowEntity", b =>
                {
                    b.Property<Guid>("ComparacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparacao_id");

                    b.Property<Guid>("CmId")
                        .HasColumnType("uuid")
                        .HasColumnName("cm_id");

                    b.Property<int>("RowPosition")
                        .HasColumnType("integer")
                        .HasColumnName("row_position");

                    b.Property<decimal>("CapacityCm3")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("capacity_cm3");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("GlassWeightG")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("glass_weight_g");

                    b.Property<decimal>("WaterWeightG")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("water_weight_g");

                    b.HasKey("ComparacaoId", "CmId", "RowPosition");

                    b.ToTable("comparacao_measurement_rows", null, t =>
                        {
                            t.HasCheckConstraint("comparacao_measurement_rows_capacity_check", "capacity_cm3 > 0");

                            t.HasCheckConstraint("comparacao_measurement_rows_glass_check", "glass_weight_g > 0");

                            t.HasCheckConstraint("comparacao_measurement_rows_position_check", "row_position >= 1");

                            t.HasCheckConstraint("comparacao_measurement_rows_weight_check", "water_weight_g > 0");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.EmailListEntity", b =>
                {
                    b.Property<Guid>("EmailListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("email_list_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("EmailListId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("email_lists_name_key");

                    b.ToTable("email_lists", null, t =>
                        {
                            t.HasCheckConstraint("email_lists_name_required_check", "btrim(name) <> ''");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.EmailListRecipientEntity", b =>
                {
                    b.Property<Guid>("EmailListRecipientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("email_list_recipient_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EmailListId")
                        .HasColumnType("uuid")
                        .HasColumnName("email_list_id");

                    b.HasKey("EmailListRecipientId");

                    b.HasIndex("EmailListId", "Address")
                        .IsUnique()
                        .HasDatabaseName("email_list_recipients_list_address_key");

                    b.ToTable("email_list_recipients", null, t =>
                        {
                            t.HasCheckConstraint("email_list_recipients_address_required_check", "btrim(address) <> ''");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.EmailTemplateEntity", b =>
                {
                    b.Property<Guid>("EmailTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("email_template_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DocumentType")
                        .HasColumnType("text")
                        .HasColumnName("document_type");

                    b.Property<Guid?>("EmailListId")
                        .HasColumnType("uuid")
                        .HasColumnName("email_list_id");

                    b.Property<string>("MachineGroup")
                        .HasColumnType("text")
                        .HasColumnName("machine_group");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("EmailTemplateId");

                    b.HasIndex("EmailListId")
                        .HasDatabaseName("IX_email_templates_email_list_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("email_templates_name_key");

                    b.ToTable("email_templates", null, t =>
                        {
                            t.HasCheckConstraint("email_templates_body_required_check", "btrim(body) <> ''");

                            t.HasCheckConstraint("email_templates_document_type_check", "document_type IS NULL OR document_type IN ('peso','pegamentos','resumo')");

                            t.HasCheckConstraint("email_templates_machine_group_check", "machine_group IS NULL OR machine_group IN ('B','C')");

                            t.HasCheckConstraint("email_templates_name_required_check", "btrim(name) <> ''");

                            t.HasCheckConstraint("email_templates_subject_required_check", "btrim(subject) <> ''");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.GlassDensitySettingEntity", b =>
                {
                    b.Property<string>("Processo")
                        .HasColumnType("text")
                        .HasColumnName("processo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("DensityGCm3")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("density_g_cm3");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Processo");

                    b.ToTable("glass_density_settings", null, t =>
                        {
                            t.HasCheckConstraint("glass_density_settings_density_check", "density_g_cm3 > 0");

                            t.HasCheckConstraint("glass_density_settings_processo_check", "processo IN ('NNPB','PS')");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.JobOnEntity", b =>
                {
                    b.Property<Guid>("JobOnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("jobon_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CopiedFromJobOnId")
                        .HasColumnType("uuid")
                        .HasColumnName("copied_from_jobon_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("machine");

                    b.Property<DateOnly?>("ProductionDate")
                        .HasColumnType("date")
                        .HasColumnName("production_date");

                    b.Property<string>("ProductionNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("production_number");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("JobOnId");

                    b.HasIndex("CopiedFromJobOnId")
                        .HasDatabaseName("IX_job_ons_copied_from_jobon_id");

                    b.HasIndex("Reference", "ProductionNumber")
                        .IsUnique()
                        .HasDatabaseName("job_ons_reference_production_number_key");

                    b.ToTable("job_ons", null, t =>
                        {
                            t.HasCheckConstraint("job_ons_machine_check", "machine IN ('B1','B2','B3','C1','C2','C3')");

                            t.HasCheckConstraint("job_ons_production_number_required_check", "btrim(production_number) <> ''");

                            t.HasCheckConstraint("job_ons_reference_required_check", "btrim(reference) <> ''");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.MachineRepairerAssignmentEntity", b =>
                {
                    b.Property<Guid>("MachineRepairerAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("machine_repairer_assignment_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("machine");

                    b.Property<Guid>("RepairerId")
                        .HasColumnType("uuid")
                        .HasColumnName("repairer_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("MachineRepairerAssignmentId");

                    b.HasIndex("Machine")
                        .IsUnique()
                        .HasDatabaseName("machine_repairer_assignments_machine_key");

                    b.HasIndex("RepairerId")
                        .HasDatabaseName("machine_repairer_assignments_repairer_idx");

                    b.ToTable("machine_repairer_assignments", null, t =>
                        {
                            t.HasCheckConstraint("machine_repairer_assignments_machine_check", "machine IN ('B1','B2','B3','C1','C2','C3')");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.MfContextEntity", b =>
                {
                    b.Property<Guid>("MfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("mf_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("JobOnId")
                        .HasColumnType("uuid")
                        .HasColumnName("jobon_id");

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uuid")
                        .HasColumnName("tool_id");

                    b.Property<string>("ToolLot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_lot");

                    b.Property<string>("ToolReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_reference");

                    b.Property<string>("ToolType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("MfId");

                    b.HasIndex("JobOnId")
                        .IsUnique()
                        .HasDatabaseName("mf_contexts_jobon_key");

                    b.HasIndex("ToolId")
                        .HasDatabaseName("IX_mf_contexts_tool_id");

                    b.ToTable("mf_contexts", null, t =>
                        {
                            t.HasCheckConstraint("mf_contexts_tool_lot_required_check", "btrim(tool_lot) <> ''");

                            t.HasCheckConstraint("mf_contexts_tool_reference_required_check", "btrim(tool_reference) <> ''");

                            t.HasCheckConstraint("mf_contexts_tool_type_check", "tool_type = 'MF'");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.PdfDirectorySettingsEntity", b =>
                {
                    b.Property<Guid>("PdfDirectorySettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("pdf_directory_setting_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BaseDirectory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_directory");

                    b.Property<bool>("Singleton")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("singleton");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("PdfDirectorySettingId");

                    b.HasIndex("Singleton")
                        .IsUnique()
                        .HasDatabaseName("pdf_directory_settings_singleton_key");

                    b.ToTable("pdf_directory_settings", null, t =>
                        {
                            t.HasCheckConstraint("pdf_directory_settings_directory_required_check", "btrim(base_directory) <> ''");

                            t.HasCheckConstraint("pdf_directory_settings_singleton_check", "singleton");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.PesoEntity", b =>
                {
                    b.Property<Guid>("PesoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("peso_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CmId")
                        .HasColumnType("uuid")
                        .HasColumnName("cm_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<decimal?>("GlassDensityGCm3")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("glass_density_g_cm3");

                    b.Property<string>("PreviousAverageWeightReference")
                        .HasColumnType("text")
                        .HasColumnName("previous_average_weight_reference");

                    b.Property<string>("PreviousProductionEndReference")
                        .HasColumnType("text")
                        .HasColumnName("previous_production_end_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pendente")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_user_id");

                    b.Property<Guid?>("ToolId")
                        .HasColumnType("uuid")
                        .HasColumnName("tool_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.Property<decimal?>("VolumeMarisaBq")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("volume_marisa_bq");

                    b.Property<decimal?>("VolumePuncaoPu")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("volume_puncao_pu");

                    b.Property<decimal>("WaterTemperature")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("water_temperature");

                    b.HasKey("PesoId");

                    b.HasIndex("CmId")
                        .HasDatabaseName("IX_pesos_cm_id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("ToolId")
                        .HasDatabaseName("IX_pesos_tool_id");

                    b.HasIndex("Status", "SubmittedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_pesos_reviewable");

                    b.ToTable("pesos", null, t =>
                        {
                            t.HasCheckConstraint("pesos_anchor_check", "((cm_id IS NULL)::int + (tool_id IS NULL)::int) = 1");

                            t.HasCheckConstraint("pesos_density_check", "glass_density_g_cm3 IS NULL OR glass_density_g_cm3 > 0");

                            t.HasCheckConstraint("pesos_marisa_volume_check", "volume_marisa_bq IS NULL OR volume_marisa_bq >= 0");

                            t.HasCheckConstraint("pesos_puncao_volume_check", "volume_puncao_pu IS NULL OR volume_puncao_pu >= 0");

                            t.HasCheckConstraint("pesos_sap_reference_check", "previous_production_end_reference IS NULL OR btrim(previous_production_end_reference) <> ''");

                            t.HasCheckConstraint("pesos_sap_weight_check", "previous_average_weight_reference IS NULL OR btrim(previous_average_weight_reference) <> ''");

                            t.HasCheckConstraint("pesos_status_check", "status IN ('pendente','aprovado','nao_aprovado')");

                            t.HasCheckConstraint("pesos_temperature_check", "water_temperature >= 5 AND water_temperature <= 35");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.PesoMeasurementRowEntity", b =>
                {
                    b.Property<Guid>("PesoMeasurementRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("peso_measurement_row_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("CapacityCm3")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("capacity_cm3");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("GlassWeightG")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("glass_weight_g");

                    b.Property<Guid>("PesoId")
                        .HasColumnType("uuid")
                        .HasColumnName("peso_id");

                    b.Property<int>("RowPosition")
                        .HasColumnType("integer")
                        .HasColumnName("row_position");

                    b.Property<decimal>("WaterWeightG")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("water_weight_g");

                    b.HasKey("PesoMeasurementRowId");

                    b.HasIndex("PesoId", "RowPosition")
                        .IsUnique()
                        .HasDatabaseName("peso_measurement_rows_peso_position_key");

                    b.ToTable("peso_measurement_rows", null, t =>
                        {
                            t.HasCheckConstraint("peso_measurement_rows_capacity_check", "capacity_cm3 > 0");

                            t.HasCheckConstraint("peso_measurement_rows_glass_check", "glass_weight_g > 0");

                            t.HasCheckConstraint("peso_measurement_rows_position_check", "row_position >= 1");

                            t.HasCheckConstraint("peso_measurement_rows_weight_check", "water_weight_g > 0");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.PesoReviewDecisionEntity", b =>
                {
                    b.Property<Guid>("PesoReviewDecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("peso_review_decision_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("decision");

                    b.Property<Guid>("PesoId")
                        .HasColumnType("uuid")
                        .HasColumnName("peso_id");

                    b.Property<int>("PesoVersionAtDecision")
                        .HasColumnType("integer")
                        .HasColumnName("pesos_version_at_decision");

                    b.Property<string>("PriorStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prior_status");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("PesoReviewDecisionId");

                    b.HasIndex("DecidedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_peso_review_decisions_decided_at");

                    b.HasIndex("DecidedByUserId");

                    b.HasIndex("PesoId")
                        .HasDatabaseName("IX_peso_review_decisions_peso_id");

                    b.ToTable("peso_review_decisions", null, t =>
                        {
                            t.HasCheckConstraint("peso_review_decisions_decision_check", "decision IN ('aprovado','nao_aprovado','reaberto')");

                            t.HasCheckConstraint("peso_review_decisions_prior_status_check", "prior_status IN ('pendente','aprovado','nao_aprovado')");

                            t.HasCheckConstraint("peso_review_decisions_reason_required_check", "(decision = 'aprovado' AND reason IS NULL) OR (decision <> 'aprovado' AND btrim(reason) <> '')");

                            t.HasCheckConstraint("peso_review_decisions_version_check", "pesos_version_at_decision >= 1");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.RepairerEntity", b =>
                {
                    b.Property<Guid>("RepairerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("repairer_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("RepairerId");

                    b.ToTable("repairers", null, t =>
                        {
                            t.HasCheckConstraint("repairers_name_required_check", "btrim(name) <> ''");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.TemplateEntity", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("template_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LandingDestinationId")
                        .HasColumnType("text")
                        .HasColumnName("landing_destination_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("TemplateId");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.TemplateModuleEntity", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("ModuleId")
                        .HasColumnType("text")
                        .HasColumnName("module_id");

                    b.Property<int>("PresentationOrder")
                        .HasColumnType("integer")
                        .HasColumnName("presentation_order");

                    b.HasKey("TemplateId", "ModuleId");

                    b.HasIndex("TemplateId", "PresentationOrder")
                        .IsUnique()
                        .HasDatabaseName("template_modules_template_order_key");

                    b.ToTable("template_modules", (string)null);
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.ToolEntity", b =>
                {
                    b.Property<Guid>("ToolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tool_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Lot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lot");

                    b.Property<string>("Processo")
                        .HasColumnType("text")
                        .HasColumnName("processo");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<string>("ToolType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ToolId");

                    b.HasIndex("Reference")
                        .HasDatabaseName("tools_reference_idx");

                    b.HasIndex("ToolType", "Reference", "Lot")
                        .IsUnique()
                        .HasDatabaseName("tools_type_reference_lot_key");

                    b.ToTable("tools", null, t =>
                        {
                            t.HasCheckConstraint("tools_lot_required_check", "btrim(lot) <> ''");

                            t.HasCheckConstraint("tools_processo_check", "processo IS NULL OR processo IN ('NNPB','PS')");

                            t.HasCheckConstraint("tools_quantity_check", "quantity IS NULL OR quantity >= 0");

                            t.HasCheckConstraint("tools_reference_required_check", "btrim(reference) <> ''");

                            t.HasCheckConstraint("tools_type_check", "tool_type IN ('CM','MF','BQ')");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.ToolMachineEntity", b =>
                {
                    b.Property<Guid>("ToolMachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tool_machine_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("machine");

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uuid")
                        .HasColumnName("tool_id");

                    b.HasKey("ToolMachineId");

                    b.HasIndex("Machine")
                        .HasDatabaseName("tool_machines_machine_idx");

                    b.HasIndex("ToolId", "Machine")
                        .IsUnique()
                        .HasDatabaseName("tool_machines_tool_machine_key");

                    b.ToTable("tool_machines", null, t =>
                        {
                            t.HasCheckConstraint("tool_machines_machine_check", "machine IN ('B1','B2','B3','C1','C2','C3')");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("AuthIdentityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_identity_id");

                    b.Property<string>("CompanyNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("UserId");

                    b.HasIndex("Active")
                        .HasDatabaseName("users_active_idx")
                        .HasFilter("\"active\"");

                    b.HasIndex("AuthIdentityId")
                        .IsUnique()
                        .HasDatabaseName("users_auth_identity_id_key");

                    b.HasIndex("CompanyNumber")
                        .IsUnique()
                        .HasDatabaseName("users_company_number_key");

                    b.HasIndex("TemplateId");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("users_auth_identity_id_required_check", "btrim(auth_identity_id) <> ''");

                            t.HasCheckConstraint("users_company_number_required_check", "btrim(company_number) <> ''");

                            t.HasCheckConstraint("users_email_required_check", "btrim(email) <> ''");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.BoquilhaEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.BqContextEntity", null)
                        .WithMany()
                        .HasForeignKey("BqId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_boquilhas_bq_contexts_bq_id");

                    b.HasOne("DMO.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_boquilhas_users_created_by_user_id");

                    b.HasOne("DMO.Infrastructure.Persistence.Entities.ToolEntity", null)
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_boquilhas_tools_tool_id");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.BoquilhaMovementAuditEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("EditedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_boquilha_movement_audit_users_edited_by_user_id");

                    b.HasOne("DMO.Infrastructure.Persistence.Entities.BoquilhaMovementEntity", null)
                        .WithMany()
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_boquilha_movement_audit_boquilha_movements_movement_id");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.BoquilhaMovementEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.BoquilhaEntity", null)
                        .WithMany()
                        .HasForeignKey("BoquilhasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_boquilha_movements_boquilhas_boquilhas_id");

                    b.HasOne("DMO.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_boquilha_movements_users_recorded_by_user_id");

                    b.HasOne("DMO.Infrastructure.Persistence.Entities.RepairerEntity", null)
                        .WithMany()
                        .HasForeignKey("RepairerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_boquilha_movements_repairers_repairer_id");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.BqContextEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.JobOnEntity", null)
                        .WithMany()
                        .HasForeignKey("JobOnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_bq_contexts_job_ons_jobon_id");

                    b.HasOne("DMO.Infrastructure.Persistence.Entities.ToolEntity", null)
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_bq_contexts_tools_tool_id");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.CmContextEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.JobOnEntity", null)
                        .WithMany()
                        .HasForeignKey("JobOnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_cm_contexts_job_ons_jobon_id");

                    b.HasOne("DMO.Infrastructure.Persistence.Entities.ToolEntity", null)
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_cm_contexts_tools_tool_id");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.ComparacaoCmSubjectEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.CmContextEntity", null)
                        .WithMany()
                        .HasForeignKey("CmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_comparacao_cm_subjects_cm_contexts_cm_id");

                    b.HasOne("DMO.Infrastructure.Persistence.Entities.ComparacaoEntity", null)
                        .WithMany()
                        .HasForeignKey("ComparacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_comparacao_cm_subjects_comparacoes_comparacao_id");

                    b.HasOne("DMO.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_comparacao_cm_subjects_users_created_by_user_id");

                    b.HasOne("DMO.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("DecidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_comparacao_cm_subjects_users_decided_by_user_id");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.ComparacaoEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("ConfirmedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_comparacoes_users_confirmed_by_user_id");

                    b.HasOne("DMO.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_comparacoes_users_created_by_user_id");

                    b.HasOne("DMO.Infrastructure.Persistence.Entities.PesoEntity", null)
                        .WithMany()
                        .HasForeignKey("PesoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_comparacoes_pesos_peso_id");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.ComparacaoMeasurementRowEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.ComparacaoCmSubjectEntity", null)
                        .WithMany()
                        .HasForeignKey("ComparacaoId", "CmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_comparacao_measurement_rows_comparacao_cm_subjects_comparacao_id_cm_id");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.EmailListRecipientEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.EmailListEntity", null)
                        .WithMany()
                        .HasForeignKey("EmailListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_email_list_recipients_email_lists_email_list_id");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.EmailTemplateEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.EmailListEntity", null)
                        .WithMany()
                        .HasForeignKey("EmailListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("email_templates_email_list_id_fkey");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.JobOnEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.JobOnEntity", null)
                        .WithMany()
                        .HasForeignKey("CopiedFromJobOnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_job_ons_job_ons_copied_from_jobon_id");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.MachineRepairerAssignmentEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.RepairerEntity", null)
                        .WithMany()
                        .HasForeignKey("RepairerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_machine_repairer_assignments_repairers_repairer_id");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.MfContextEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.JobOnEntity", null)
                        .WithMany()
                        .HasForeignKey("JobOnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_mf_contexts_job_ons_jobon_id");

                    b.HasOne("DMO.Infrastructure.Persistence.Entities.ToolEntity", null)
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_mf_contexts_tools_tool_id");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.PesoEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.CmContextEntity", null)
                        .WithMany()
                        .HasForeignKey("CmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_pesos_cm_contexts_cm_id");

                    b.HasOne("DMO.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_pesos_users_created_by_user_id");

                    b.HasOne("DMO.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_pesos_users_submitted_by_user_id");

                    b.HasOne("DMO.Infrastructure.Persistence.Entities.ToolEntity", null)
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_pesos_tools_tool_id");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.PesoMeasurementRowEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.PesoEntity", null)
                        .WithMany()
                        .HasForeignKey("PesoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_peso_measurement_rows_pesos_peso_id");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.PesoReviewDecisionEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("DecidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_peso_review_decisions_users_decided_by_user_id");

                    b.HasOne("DMO.Infrastructure.Persistence.Entities.PesoEntity", null)
                        .WithMany()
                        .HasForeignKey("PesoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_peso_review_decisions_pesos_peso_id");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.TemplateModuleEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.TemplateEntity", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.ToolMachineEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.ToolEntity", "Tool")
                        .WithMany("Machines")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.TemplateEntity", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.ToolEntity", b =>
                {
                    b.Navigation("Machines");
                });
#pragma warning restore 612, 618
        }
    }
}
